export const EXERCISES = [
  {
    id: "e1",
    type: "mirror",
    icon: "🪞",
    title: "Le Miroir",
    duration: "3 min",
    durationSecs: 180,
    description: "Répète la phrase avec la même intonation. Le miroir forge la confiance.",
    phrase: "\"Permettez-moi de vous poser une question directe : qu'est-ce qui vous retient de passer à la fibre aujourd'hui ?\"",
    tip: "Maintiens le contact visuel avec toi-même. Pas de regard fuyant.",
    color: "#FF5C35",
    xp: 30,
  },
  {
    id: "e2",
    type: "improvisation",
    icon: "⚡",
    title: "L'Impro 60s",
    duration: "1 min",
    durationSecs: 60,
    description: "Parle pendant 60 secondes sans t'arrêter. L'hésitation est l'ennemi.",
    phrase: "Sujet : Explique pourquoi la connexion internet est devenue indispensable pour une famille moderne.",
    tip: "Si tu bloques : \"Et ce qui est intéressant c'est que...\"",
    color: "#FFB800",
    xp: 40,
  },
  {
    id: "e3",
    type: "silence",
    icon: "🤫",
    title: "Le Silence Stratégique",
    duration: "5 min",
    durationSecs: 300,
    description: "Après chaque affirmation forte, impose 3 secondes de silence.",
    phrase: "\"Ce que je vous propose change vraiment les choses... [3s] Et voici pourquoi.\"",
    tip: "Le silence après une affirmation forte la multiplie par 10.",
    color: "#3B82F6",
    xp: 25,
  },
  {
    id: "e4",
    type: "diction",
    icon: "🎵",
    title: "Diction & Rythme",
    duration: "4 min",
    durationSecs: 240,
    description: "Lis ces virelangues 3x de suite en accélérant à chaque répétition.",
    phrase: "\"Cinq singes savants saisissant six savantes solutions sans sourciller.\"",
    tip: "Articulation parfaite = voix qui commande le respect.",
    color: "#A855F7",
    xp: 20,
  },
];
